variables:
  - &file Containerfile
  - &repo fuwafuwalabs/padm_exporter

steps:
  - name: dry run
    when:
      - event:
          - pull_request
      - event:
          - manual
        evaluate: 'CI_COMMIT_BRANCH != CI_REPO_DEFAULT_BRANCH'
    image: woodpeckerci/plugin-kaniko:2.2.1@sha256:befd01f73ddea45a8ca44d4a2ec4e5e122f23a7ad65b4aa47986fe783beee219
    settings:
      dockerfile: *file
      dry_run: true

  - name: publish container
    when:
      - event:
          - push
          - tag
          - cron
        branch:
          - ${CI_REPO_DEFAULT_BRANCH}
        cron: "daily build"
    image: woodpeckerci/plugin-kaniko:2.2.1@sha256:befd01f73ddea45a8ca44d4a2ec4e5e122f23a7ad65b4aa47986fe783beee219
    settings:
      dockerfile: *file
      repo: *repo
      auto_tag: true
      registry:
        from_secret: REGISTRY
      username:
        from_secret: REGISTRY_USER
      password:
        from_secret: REGISTRY_PASS
