when:
  - event:
      - push
      - pull_request
      - tag
      - manual
      - cron
    cron: "daily build"

variables:
  - &file Containerfile
  - &repo fuwafuwalabs/padm_exporter

steps:
  - name: dry run
    when:
      - event:
          - pull_request
      - event:
          - push
          - manual
        evaluate: 'CI_COMMIT_BRANCH != CI_REPO_DEFAULT_BRANCH'
    image: woodpeckerci/plugin-kaniko:1.3.0@sha256:e7a5e8438f20e722c1c9527f8d6d36163cf26e9dd55b838301bb9d5d3a30f994
    settings:
      dockerfile: *file
      dry_run: true

  - name: publish container
    when:
      - event:
          - push
          - tag
          - cron
        branch:
          - ${CI_REPO_DEFAULT_BRANCH}
    image: woodpeckerci/plugin-kaniko:1.3.0@sha256:e7a5e8438f20e722c1c9527f8d6d36163cf26e9dd55b838301bb9d5d3a30f994
    settings:
      dockerfile: *file
      repo: *repo
      auto_tag: true
      registry:
        from_secret: REGISTRY
      username:
        from_secret: REGISTRY_USER
      password:
        from_secret: REGISTRY_PASS
